### PR TITLE
URP 13/14 support

### PR DESCRIPTION
**Pull request by Milk-Drinker01**
Adds support for URP 13/14. 
Use RTHandles instead of RenderTargetHandle.
Added a demo scene.

### CODE REVIEW

**Comment by JoshuaLim007** [comment]
I'm getting slightly slower performance. Around 0.3 to 0.8 ms difference when testing this on URP 12.  My only guess is the change to RTHandles. Maybe there is a redundant allocation happening? cmd.GetTemporaryRT and RTHandles.Alloc are invoked in the Configure phase in LimSSR.cs. This could be a double allocation. Not entirely sure. 

Another thing is that the SSR does not work during play mode on URP 14 Unity 2022 on "Play Maximized". Could you look into that. After these bugs are fixed, we can safely merge into the main branch.

**Comment by Milk-Drinker01** [comment]
I suspect the lower performance comes from this extra blit pass. For some reason, in URP 14, unless I blit the camera color target to the tempRenderTarget before the second pass, the output is black. even after reverting back to using RenderTargetHandle, this second pass is required on URP 14, and the performance is about the same. Though, on my 2080 super, even at 4k, .01 stride, and 512 max steps, the command buffer is taking only .01 ms, which makes it pretty hard to directly compare performance. Maybe you will have a better idea why this extra blit is required? Maybe its a unity bug. I tested on 2022.2.2f1

Screenshot_11

**Comment by Milk-Drinker01** [comment]
nevermind, im dumb. i was profiling the wrong thing. im looking into it now

**Comment by JoshuaLim007** [comment]
No you actually brought something up that I skipped over. It is strange that it needs that extra blit. Can you experiment with by changing the source duplicate with a different name other than "_MainTex". _MainTex is usually reserved for the source render texture when blitting. Could be causing problems by having a texture initialized as _MainTex which makes it so that we need another blit before the second pass even though we duplicated it already during the configure phase.

sc1

On the side note. This SSR algorithm doesn't use a depth pyramid so the performance will drastically suffer with higher max step. I'm currently looking into implementing my own depth pyramid since Unity URP doesn't provide one yet.

**Comment by Milk-Drinker01** [comment]
I have ran some performance tests. All tests were done in 4k, 0.01 step stride length, 512 max steps, and 0 down sample. 

The results show that: 

- RenderTargetHandle and RTHandle have performance within margin of error, which is good, since RenderTargetHandle is obsolete in URP 14. 
- URP 14 is consistently 1.3ms faster (about 10%)
- The extra blit pass adds an additional .3ms at these settings

urp12-targethandle-extrablit
urp12-targethandle-noblit
urp12-rthandle
urp14-rthandle
urp14-targethandle

Changing the temp RT name from _MainTex did not remove the requirement for the extra blit pass, I tried it before the PR, but double checked just now as a sanity check.

**Comment by JoshuaLim007** [comment]
Okay, so I looked through the issue with not showing up on maximize play mode and found the issue. It turns out we don't even need to use RTHandles, look at the image circled in red. We can just do shader.propertyid and then get temporaryrt without having to allocate via RTHandle class. Like I expected, Unity was doing a redundant rt allocation. Also found out that the blit in the configure function cmd.Blit(Source, tempRenderID) does not blit correctly, that's why the screen is just black without an extra blit in the Execute function. I'm going to merge the PR and make does additional changes on top of yours. 

sc2

**Pull request merged**
